export const projectData = [
  {
    title: 'SkyNet Watch',
    language: 'HTML, CSS, JavaScript, MySQL, Handlebars, NodeJS, Express,  ',
    liveUrl: 'https://polar-atoll-04436.herokuapp.com/',
    gitHubUrl: 'https://github.com/dlope0831/SkyNet-Watch',
    img: 'https://i.imgur.com/doHzk1k.png',
    alt: 'test img',
    isNew: true,
  },
  {
    title: 'Music App',
    language: 'HMTL, CSS, JavaScript',
    liveUrl: 'https://jlara65.github.io/music-player/',
    gitHubUrl: 'https://github.com/jlara65/music-player',
    img: 'https://i.imgur.com/uxokAin.png',
    alt: 'A preview of the Music App, a project that utilizes a demo music',
    isNew: false,
  },
  {
    title: 'Text Editor',
    language:
      'HTML, CSS, JavaScript, IndexedDB, Webpack, Manifest, Service Worker ',
    liveUrl: 'https://fathomless-mountain-60724.herokuapp.com/',
    gitHubUrl: 'https://github.com/jlara65/text-editor-pwa',
    img: 'https://i.imgur.com/3qNCZ4d.png',
    alt: 'A preview of the text editor, a project that create text editor either online or offline',
    isNew: false,
  },
  {
    title: 'Tech Blog',
    language: 'HTML, CSS, JavaScript, MySQL, Handlebars, sequelize, express',
    liveUrl: 'https://jl-tech-blog.herokuapp.com/',
    gitHubUrl: 'https://github.com/jlara65/tech-blog',
    img: 'https://i.imgur.com/n5r2Rlf.png',
    alt: 'A preview of the Tech Blog, a project that allow people post their blog about technology',
    isNew: false,
  },
  {
    title: 'test first project',
    language: 'HTML, CSS, JavaScript, MySQL, Handlebars, sequelize, express',
    liveUrl: 'https://thawing-cliffs-68050.herokuapp.com/',
    gitHubUrl: 'https://github.com/jlara65/note-taker',
    img: 'https://i.imgur.com/tXTxJ5e.png',
    alt: 'A preview of the note taker, a project that allow people to add note',
    isNew: false,
  },
  {
    title: 'Weather Dashboard',
    language: 'HTML, CSS, JavaScript',
    liveUrl: 'https://jlara65.github.io/weather-dashboard/',
    gitHubUrl: 'https://github.com/jlara65/weather-dashboard',
    img: 'https://i.imgur.com/S2pPWsV.png',
    alt: 'A preview of the weather dashboard, a project that allow people to look up the city to view the weather forecast',
    isNew: false,
  },
  {
    title: 'Work Day Scheduler',
    language: 'HTML, CSS, JavaScript',
    liveUrl: 'https://jlara65.github.io/work-day-scheduler/',
    gitHubUrl: 'https://github.com/jlara65/work-day-scheduler',
    img: 'https://i.imgur.com/ziniftF.png',
    alt: 'A preview of the Work Day Scheduler, a project that allow people to add daily planner to track their events',
    isNew: false,
  },
  {
    title: 'Code Quiz',
    language: 'HTML, CSS, JavaScript',
    liveUrl: 'https://jlara65.github.io/code-quiz/',
    gitHubUrl: 'https://github.com/jlara65/code-quiz',
    img: 'https://i.imgur.com/PCuwirY.png',
    alt: 'A preview of the Code Quiz, a project that allow people to take quiz about code',
    isNew: false,
  },
  {
    title: 'Password Generator',
    language: 'HTML, CSS, JavaScript',
    liveUrl: 'https://jlara65.github.io/password-generator/',
    gitHubUrl: 'https://github.com/jlara65/password-generator',
    img: 'https://i.imgur.com/HxnjNbn.png',
    alt: 'A preview of the password generator, a project that allow people generator the password',
    isNew: false,
  },
  {
    title: 'Run Buddy',
    language: 'HTML, CSS',
    liveUrl: 'https://jlara65.github.io/run-buddy/run-buddy/',
    gitHubUrl: 'https://github.com/jlara65/run-buddy',
    img: 'https://i.imgur.com/LUSPFt0.png',
    alt: 'A preview of the run buddy, a project that display only html and css page',
    isNew: false,
  },
  {
    title: 'Photo Port',
    language: 'HTML, CSS, Javascript, React',
    liveUrl: 'https://jlara65.github.io/photo-port/',
    gitHubUrl: 'https://github.com/jlara65/photo-port',
    img: 'https://i.imgur.com/LSPc58P.png',
    alt: 'A preview of the photo port page, a project that display about photography business',
    isNew: false,
  },
];
